import { Albert_Sans } from 'next/font/google'

import '@/styles/global.css'
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import HeaderMobileWrapper from "@/components/wrapper/layout/headerMobile";

const albertSans = Albert_Sans({
  subsets: ['latin'],
  weights: ['400', '500', '700'],
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={albertSans.className}>
      <body>

        {/* Desktop Header */}
        <div className="hidden lg:block">
          <Header />
        </div>

        {/* Mobile Header */}
        <HeaderMobileWrapper />

        {children}
        <Footer />
      </body>
    </html>
  );
}
