import {
  FaKey,
  FaBuilding,
  FaChartBar,
  FaChartLine,
  FaExchangeAlt,
  FaUserCheck,
  FaBolt,
  FaLightbulb,
  FaHandSparkles,
  FaBullseye,
  FaHeart,
  FaSmile,
  FaTools,
  FaStar,
  FaSearch,
  FaCheckCircle,
  FaUsers,
  FaGlobe,
  FaEnvelope,
  FaMobileAlt,
  FaClipboardCheck,
  FaShieldAlt,
  FaWallet,
  FaPlane,
  FaShoppingCart,
  FaCar,
  FaLaptopCode,
  FaSignal,
  FaNetworkWired,
  FaUser,
  FaPiggyBank,
  FaRegLightbulb,
  FaClipboardList,
  FaRegCheckCircle,
  FaPhone,
  FaMapMarkerAlt
} from "react-icons/fa";
import { LuChartSpline } from "react-icons/lu";
import { GiProgression } from "react-icons/gi";

export const iconMap = {
  FaKey: <FaKey className="text-primary" />,
  FaBuilding: <FaBuilding className="text-purple-600" />,
  FaChartBar: <FaChartBar className="text-primary" />,
  FaChartLine: <FaChartLine size={24} className="text-primary" />,
  FaExchangeAlt: <FaExchangeAlt size={24} className="text-primary" />,
  FaUserCheck: <FaUserCheck size={24} className="text-primary" />,
  FaBolt: <FaBolt size={22} className="text-white" />,
  FaLightbulb: <FaLightbulb className="text-primary" />,
  FaHandSparkles: <FaHandSparkles className="text-primary" />,
  FaBullseye: <FaBullseye size={24} className="text-primary" />,
  FaHeart: <FaHeart size={24} className="text-primary" />,
  FaSmile: <FaSmile size={24} className="text-primary" />,
  FaTools: <FaTools size={24} className="text-primary" />,
  FaStar: <FaStar size={24} className="text-primary" />,
  FaSearch: <FaSearch size={24} className="text-primary" />,
  FaCheckCircle: <FaCheckCircle size={24} className="text-primary" />,
  FaUsers: <FaUsers size={24} className="text-primary" />,
  FaGlobe: <FaGlobe size={24} className="text-primary" />,
  FaEnvelope: <FaEnvelope size={24} className="text-primary" />,
  FaMobileAlt: <FaMobileAlt size={24} className="text-primary" />,
  FaClipboardCheck: <FaClipboardCheck size={24} className="text-primary" />,
  FaShieldAlt: <FaShieldAlt size={24} className="text-primary" />,
  FaWallet: <FaWallet size={24} className="text-primary" />,
  FaPlane: <FaPlane size={24} className="text-primary" />,
  FaShoppingCart: <FaShoppingCart size={24} className="text-primary" />,
  FaCar: <FaCar size={24} className="text-primary" />,
  FaLaptopCode: <FaLaptopCode size={24} className="text-primary" />,
  FaSignal: <FaSignal size={24} className="text-primary" />,
  FaNetworkWired: <FaNetworkWired size={24} className="text-primary" />,
  FaLightbulb: <FaRegLightbulb className="text-primary" />,
  FaPiggyBank: <FaPiggyBank className="text-primary" />,
  FaUser: <FaUser className="text-primary" />,
  FaUsers: <FaUsers className="text-primary" />,
  GiProgression: <GiProgression className="text-primary" />,
  FaClipboardList: <FaClipboardList size={24} className="text-white" />,
  FaCheckCircle: <FaRegCheckCircle size={24} className="text-white" />,
  LuChartSpline: <LuChartSpline size={24} className="text-white" />,
  FaPhone: <FaPhone size={24} className="text-primary" />,
  FaMapMarkerAlt: <FaMapMarkerAlt size={24} className="text-primary" />,
};
